# Add 'repo' label to any root file changes
repo:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "*"

# Add 'circleci' label to any change to .circleci files
circleci:
  - any:
      - changed-files:
        - any-glob-to-any-file:
             - ".circleci/**/*"

# Add 'actions' label to any change to .github files
actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/**/*"

# Add 'assets' label to any change to assets files
assets:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "assets/**/*"

# Add 'datatypes' label to any change to built-in-datatypes files
datatypes:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "built-in-datatypes/**/*"

# Add 'charts' label to any change to charts files
charts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "charts/**/*"

# Add 'danger' label to any change to danger files
danger:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "danger/**/*"

# Add 'doc' label to any change to doc files
doc:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "doc/**/*"

# Add 'docs' label to any change to docs files
docs:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docs/**/*"

# Add 'drivers' label to any change to drivers files
drivers:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "drivers/**/*"

# Add 'eclipse-cheatsheets' label to any change to eclipse-cheatsheets-to-dita-to-pdf files
eclipse-cheatsheets:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "eclipse-cheatsheets-to-dita-to-pdf/**/*"

# Add 'flicker' label to any change to flicker-diff files
flicker:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "flicker-diff/**/*"

# Add 'govegas' label to any change to govegas files
govegas:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "govegas/**/*"

# Add 'hashcheck' label to any change to hashcheck files
hashcheck:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "hashcheck/**/*"

# Add 'logorama' label to any change to logorama files
logorama:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "logorama/**/*"

# Add 'losroques' label to any change to losroques files
losroques:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "losroques/**/*"

# Add 'macewindu' label to any change to macewindu files
macewindu:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "macewindu/**/*"

# Add 'pdfstar' label to any change to pdfstar files
pdfstar:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "pdfstar/**/*"

# Add 'railsdudes' label to any change to railsdudes files
railsdudes:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "railsdudes/**/*"

# Add 'ruby-eclipse-cheatsheets' label to any change to ruby-eclipse-cheatsheets-to-dita files
ruby-eclipse-cheatsheets:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "ruby-eclipse-cheatsheets-to-dita/**/*"

# Add 'ruby-strip' label to any change to ruby-strip files
ruby-strip:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "ruby-strip/**/*"

# Add 'rubycritic' label to any change to rubycritic files
rubycritic:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "rubycritic/**/*"

# Add 'rubytart' label to any change to rubytart files
rubytart:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "rubytart/**/*"

# Add 'scrapers' label to any change to scrapers files
scrapers:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "scrapers/**/*"

# Add 'seek' label to any change to seek files
seek:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "seek/**/*"

# Add 'tests' label to any change to tests files
tests:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "tests/**/*"

# Add 'well-formed' label to any change to well-formed files
well-formed:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "well-formed/**/*"

# Add 'workers.dev' label to any change to workers.dev files
workers.dev:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "workers.dev/**/*"

# Add 'xsl-schema-sort' label to any change to xsl-schema-sort files
xsl-schema-sort:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "xsl-schema-sort/**/*"
