version: 2

build:
  os: ubuntu-22.04

# Build documentation in the docs/source/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

  # If using Sphinx, optionally build your docs in additional formats such as PDF
formats: all

python:
  install:
    - requirements: doc/requirements.txt
