AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.2.1

### LAYOUT
Layout/LineLength:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/DuplicateBranch:
  Enabled: false

### METRICS
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 45

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 130

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

### STYLING
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  Enabled: true

Metrics/ClassLength:
  Max: 120
